<!DOCTYPE html>
<html lang="en">
  <head>
    <title>NekoMimi =UwU=</title>
    <meta charset="UTF-8">

    <meta name="theme-color" media="(prefers-color-scheme: dark)" content="#232232">
    <meta name="theme-color" content="#1E1D2D">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="stylesheet.css" rel="stylesheet">
  </head>
  <body>


  <div class="sidebar">
    <img class="sb-brand" src="http://nekomimi.tilde.team/neko.png" alt="my character oc">
    <div class = "sb-brand-outliner"></div>
    <div class ="hr"></div>
    <div class = "sb-container sb-container-d"><a href="#i">!</a></div>
    <div class = "sb-container sb-container-d"><a href="#q">?</a></div>
    <div class = "sb-container sb-container-d"><a href="#l">@</a></div>
    <div class = "hr"></div>
    <div class = "sb-container sb-container-dc"><a href="http://nekomimi.tilde.team/store">v</a></div><br>
  </div>

  <div class="main" id="i">
    <div class="nekomimi">NekoMimi</div>
    <div class="aboutme">
      Howdy! I'm Neko, a software dev and an artist!<br>
      from a full-stack web dev to a general C++ developer<br>
      my main interests are networking and remote apps
      <div class="dropper"><br><br><br>v</div>
    </div>

    <div class="term-flexer" id="q">

    <!- autogenerated by flask ->
<div class='window'><div class='window-bar'><div class='dots'></div></div><div class='heading'>GitHub</div><br>Projects: 8<br>Organizations: The NekOS Project, NekoLabs</div><div class='window'><div class='window-bar'><div class='dots'></div></div><div class='heading'>Languages</div><br>C++ , Python , Java , JS , PHP , HTML5 w CSS3</div><div class='window'><div class='window-bar'><div class='dots'></div></div><div class='heading'>System stats</div><br>Host: HP Pavilion DV4000<br>OS: GNU/NekOS<br>Kernel: NekoKernel-5.19.1-32bit<br>DE: NekoExperience</div><div class='window'><div class='window-bar'><div class='dots'></div></div><div class='heading'>Main Projects</div><br>* The NekOS Project<br>* Nyasshu<br>* NekoTPy<br>* NekoMimi</div>
    
    </div>

    <div class="hr" style="margin-top: 30px;"></div>

    <div class="links" id="l">
      <div class="sb-container sb-container-d l-m">
        <a href="https://github.com/nekomimiofficial">GitHub</a>
      </div>
      <div class="sb-container sb-container-d l-m">
        <a href="mailto://nekomimi@tilde.team">Email</a>
      </div>
      <div class="sb-container sb-container-dr l-m">
        <a href="https://youtube.com/@NekoMimiOfficial">YouTube</a>
    </div>
    <div class="sb-container sb-container-d l-m">
      <a rel="me" href="https://sakurajima.moe/@nekomimi">Mastodon</a>
    </div>
    </div>

    <br>

    <div class="rand">
    <div class="lnks">
      <h3>Links</h3>
      Discord: @nekomimiofficial<br>
      Telegram: @nekomimiofficial<br>
      Instagram: @nekomimiofficial<br>
    </div>
    </div>

    <div class="hr" style="margin-bottom: 30px;"></div>

    <div class="rand">
      <div>
      <h3 class="h3o">My ArtWorks API</h3>
      <img class="r-cont" id="API-img" src="<?PHP echo file_get_contents('http://nekomimi.tilde.team/API/v1'); ?>" >
        <div class="pby">Powered by NekoLabs</div>
      </div>
    </div>

    <br>

    <div class="rand">
      <div class="mono">
        NekoMimi@NekoLabs 2023
      </div>
      <p id="DBG"></p>
    </div>

  </div>
  
  <!- What do you think you'll find here? I'm 100% free javcascript! ->

  </body>
</html>
